<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Ontology Design for Music Player | Martin Doubravsky | Bachelor Thesis @ DCGI, FEE, CTU, Prague</title>
    <!--
		2009 © Martin Doubravský
 
		Cassette image by jazza (http://www.sxc.hu/profile/jazza)
		Social.me icons by jwloh (http://jwloh.deviantart.com/)
	--> 
    <meta name="robots" content="noindex,nofollow"/>
    <link rel="stylesheet" type="text/css" media="screen,projection" href="http://localhost/MusicPlayerOntology/MusicPlayerOntology/document_root/css/mpo.css" />
    <!--[if IE]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <link rel="stylesheet" type="text/css" media="screen,projection" href="http://localhost/MusicPlayerOntology/MusicPlayerOntology/document_root/css/ie.css" />
    <![endif]-->
    <script src="http://www.google.com/jsapi"></script>
    <script>
        google.load("jquery", "1.3.2");
    </script>
    <script src="http://localhost/MusicPlayerOntology/MusicPlayerOntology/document_root/js/mpo.js" type="text/javascript"></script>
	<script src="http://localhost/MusicPlayerOntology/MusicPlayerOntology/document_root/js/modernizr-1.1.min.js" type="text/javascript"></script>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
</head>
<body class=<?php if(!$interpret && !$genre && !$instrument && !$song){?>"hp"<?php }else {?>"results"<?php }?>>
<div id="page"><div id="page-in">
<h1><a href="./">Ontology Design for Music Player</a></h1>

<div id="searchMethod">
    <a href="#interpret">interpret</a>
    <a href="#genre">genres</a>
    <a href="#instrument">instruments</a>
    <a href="#song">song</a>
</div>

<div id="forms">
    <form action="index.php" method="get">
        <fieldset>
            <label for="interpret">Search for Interprets</label> <input type="text" id="interpret" name="interpret" />
            <input type="submit" value="Search" />
            <small>e.g. Michael Jackson, The Beatles..</small>
        </fieldset>
    </form>
    <form action="index.php" method="get">
        <fieldset>
            <label for="genre">Search by genre (e.g. Urban, Pop/Rock..)</label> <input type="text" id="genre" name="genre" />
            <input type="submit" value="Search" />
            <small>You can type more genres (separated by comma, dot or semicolon).</small>
        </fieldset>
    </form>
    <form action="index.php" method="get">
        <fieldset>
            <label for="instrument">Search by Instrument (e.g. Guitar, Harmonica..)</label> <input type="text" id="instrument" name="instrument" />
            <input type="submit" value="Search" />
            <small>You can type more instruments (separated by comma, dot or semicolon).</small>
        </fieldset>
    </form>
    <form action="index.php" method="get">
        <fieldset>
            <label for="song">Song or album</label> <input type="text" id="song" name="song" />
            <input type="submit" value="Search" />
            <small>For instance My Heart Will Go On, Care About Us, ..</small>
        </fieldset>
    </form>
</div>

<?php if($artist OR $band){

    include TEMPLATE_DIR . 'interprets.phtml';

} else if($genre){

    include TEMPLATE_DIR . 'genres.phtml';
    
} else if($instrument){

    include TEMPLATE_DIR . 'instruments.phtml';
    
} else if($song){

    include TEMPLATE_DIR . 'songs.phtml';
    
}?>

<?php if($errorMsg) echo "<div class=\"err\">".$errorMsg."</div>";?>

</div></div>
<footer>
    <p><a href="http://www.cvut.cz">Czech Technical University in Prague</a></p>
    <p><a href="http://fel.cvut.cz">Faculty of Electrical Engineering</a></p>
    <p><a href="http://dcgi.felk.cvut.cz">Department of Computer Graphics and Interaction</a></p>
    
    <h4>Bachelor thesis <br/><a href="http://www.scribd.com/pdf-file-will-be-here">Ontology Design for Music Player</a> <span>(cs)</span></h4>
    <ul>
        <li><a href="http://owl.cs.manchester.ac.uk/browser/manage/?action=load&clear=true&uri=http://martindoubravsky.cz/ctu/musicplayerontology.owl">Ontology online browser</a>,</li>
        <li><a href="musicplayerontology.owl">source code</a>,</li>
        <li><a href="musicplayerontology_h.png">schema</a>&#160;|</li>
        <li>Project <a href="http://github.com/matesd/MusicPlayerOntology/tree/master">github</a>&#160;|</li>
        <li>Build on <a href="http://arc.semsol.org/">ARC</a></li>
    </ul>
    <p>&copy; 2009 <a href="http://martindoubravsky.cz/">Martin Doubravský</a>, <a href="mailto:doubrma1@fel.cvut.cz">mail</a>
        <a href="http://twitter.com/matesd/"><img src="document_root/img/twitter.png" width="16" height="16" alt="twitter"/></a>
        <a href="http://www.facebook.com/martindoubravsky"><img src="document_root/img/facebook.png" width="16" height="16" alt="facebook"/></a>
        <a href="http://www.linkedin.com/in/martindoubravsky"><img src="document_root/img/linkedin.png" width="16" height="16" alt="linkedin"/></a>
    </p> 
</footer>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-11847658-2");
pageTracker._trackPageview();
} catch(err) {}</script>
</body>
</html>