<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Ontology Design for Music Player | Martin Doubravsky | Bachelor Thesis @ DCGI, FEE, CTU, Prague</title>
    <!--
		2009 © Martin Doubravský
 
		Cassette image by Jay Simmons aka jazza from free stock photo site Stock.XCHNG (http://www.sxc.hu)
	--> 
    <meta name="robots" content="noindex,nofollow"/>
    <link rel="stylesheet" type="text/css" media="screen,projection" href="http://localhost/MusicPlayerOntology/MusicPlayerOntology/document_root/css/mpo.css" />
    <!--[if IE]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="http://www.google.com/jsapi"></script>
    <script>
        google.load("jquery", "1.3.2");
    </script>
    <script src="http://localhost/MusicPlayerOntology/MusicPlayerOntology/document_root/js/mpo.js" type="text/javascript"></script>
	<script src="http://localhost/MusicPlayerOntology/MusicPlayerOntology/document_root/js/modernizr-1.0.min.js" type="text/javascript"></script>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
</head>
<body>

<div id="todo" style="position:absolute">todo:
<ul>
    <li>sticky footer</li>
    <li>search result design (smaller header)</li>
    <li>label length</li>
    <li>results design</li>
    <li>link colors</li>
</ul>
</div>
<h1>Ontology Design for Music Player</h1>

<div id="searchMethod">
    <a href="#interpret">interpret</a>
    <a href="#genre">genres</a>
    <a href="#instrument">instruments</a>
    <a href="#song">song</a>
</div>

<div id="forms">
    <form action="index.php" method="get">
        <fieldset>
            <label for="interpret">Search for Interprets</label> <input type="text" id="interpret" name="interpret" />
            <input type="submit" value="Search" />
            <small>For instance Michael Jackson, The Beatles, ..</small>
        </fieldset>
    </form>
    <form action="index.php" method="get">
        <fieldset>
            <label for="genre">Search by genre. For instance Urban, Contemporary Pop/Rock, ..</label> <input type="text" id="genre" name="genre" />
            <input type="submit" value="Search" />
            <small>You can type more genres (separated by comma, dot or semicolon)</small>
        </fieldset>
    </form>
    <form action="index.php" method="get">
        <fieldset>
            <label for="instrument">Search by Instrument. For instance Guitar, Harmonica, ..</label> <input type="text" id="instrument" name="instrument" />
            <input type="submit" value="Search" />
            <small>You can type more instruments (separated by comma, dot or semicolon).</small>
        </fieldset>
    </form>
    <form action="index.php" method="get">
        <fieldset>
            <label for="song">Song or album</label> <input type="text" id="song" name="song" />
            <input type="submit" value="Search" />
            <small>For instance My Heart Will Go On, Care About Us, ..</small>
        </fieldset>
    </form>
</div>

<?php if($artist OR $band){

    include TEMPLATE_DIR . 'interprets.phtml';

} else if($genre){

    include TEMPLATE_DIR . 'genres.phtml';
    
} else if($instrument){

    include TEMPLATE_DIR . 'instruments.phtml';
    
} else if($song){

    include TEMPLATE_DIR . 'songs.phtml';
    
}?>

<?php if($errorMsg) echo "<div class=\"err\">".$errorMsg."</div>";?>

 
<footer>
<ul>
    <li><a href="http://owl.cs.manchester.ac.uk/browser/manage/?action=load&clear=true&uri=http://martindoubravsky.cz/ctu/musicplayerontology.owl">Ontology online browser</a></li>
    <li><a href="http://martindoubravsky.cz/ctu/musicplayerontology.owl">Ontology source code</a></li>
    <li><a href="http://martindoubravsky.cz/ctu/musicplayerontology_h.png">Ontology image (horizontal)</a></li>
    <li><a href="http://martindoubravsky.cz/ctu/musicplayerontology_v.png">Ontology image (vertical)</a></li>
</ul>
<p><a href="http://github.com/matesd/MusicPlayerOntology/tree/master">github</a> <a href="http://arc.semsol.org/">ARC</a></p>
<p>
    Bachelor thesis <a href="http://www.scribd.com/pdf-file-will-be-here">Ontology Design for Music Player</a>,
    author Martin Doubravský <a href="mailto:doubrma1@fel.cvut.cz">doubrma1@fel.cvut.cz</a> @ 
    <a href="http://dcgi.felk.cvut.cz">Department of Computer Graphics and Interaction</a> @
    <a href="http://fel.cvut.cz">Faculty of Electrical Engineering</a> @
    <a href="http://www.cvut.cz">Czech Technical University in Prague</a>
</p>
</footer>


<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-11847658-2");
pageTracker._trackPageview();
} catch(err) {}</script>
</body>
</html>