<?php 
if($moreGenres){
    echo "moreGenres:<br/>";
    foreach ($moreGenres as $g){
        echo $g."<br/>";
    }
}
if($uniqueGenre){
    echo "uniqueGenre:<br/>";
    foreach ($uniqueGenre as $g){
        echo $g."<br/>";
    }
}
if($unknownGenre){
    echo "noGenres:<br/>";
    foreach ($unknownGenre as $g){
        echo $g."<br/>";
    }
}
print_r(array_values($existingGenres));

if(!$artistGenreMismatch){?>
<div id="results">
    <h2>Artists with <em><?php echo htmlspecialchars($genreOutput)?></em> genre<?php if($pluralGenre==1){?>s<?php } ?></h2>
    <?php if($moreGenres){
        
    } ?>
    <section>
        <h3>Artists</h3>
        <ul>
        <?php
        foreach($artistGenre as $a){
            if(preg_match ('/SoloArtist$/',$a["type"])){
                echo "<li><a href=\"?interpret=".htmlspecialchars($a["artistName"])."\">".htmlspecialchars($a["artistName"])."</a></li>";
            }
        }
        ?>
        </ul>
    </section>
    <section>
        <h3>Bands</h3>
        <ul>
        <?php
        foreach($artistGenre as $a){
            if(preg_match ('/Band$/',$a["type"])){
                echo "<li><a href=\"?interpret=".htmlspecialchars($a["artistName"])."\">".htmlspecialchars($a["artistName"])."</a></li>";
            }
        }
        ?>
        </ul>
    </section>
</div>
<?php }