<?php if(!$instrumentsMismatch){?>
<div id="results">
    <?php if($unknownInstrumentMsg) echo "<div class=\"err\">".$unknownInstrumentMsg."</div>"; ?>
    <h2>Artists who play <?php echo $instrumentOutput;?></h2>
    <div><small>
    <?php if($moreInstSearch){
        echo "Found instruments: ";
        foreach($moreInstSearch as $m){
            echo "<a href=\"?instrument=".htmlspecialchars($m["instName"])."\">".htmlspecialchars($m["instName"])."</a>, ";
        }
    }?>
    </small></div>
    <section>
        <ul>
        <?php
        foreach($instruments as $a){
            echo "<li><a href=\"?interpret=".htmlspecialchars($a["artistName"])."\">".htmlspecialchars($a["artistName"])."</a></li>";
        }
        ?>
        </ul>
    </section>
</div>
<?php } ?>