<?php if($moreInterprets){ ?>
    <div id="results">
        <h2>Who do you want to find?</h2> 
        <ul>
        <?php
        foreach($possibleInterprets as $pos){
            echo "<li><a href=\"?interpret=".htmlspecialchars($pos["posIntName"])."\">".htmlspecialchars($pos["posIntName"])."</a></li>";
        }?>
        </ul>
    </div>
        <?php
    } else {
        echo "<h2>".$theOnlyOneName."</h2>";
    ?>
    
    <div id="results">
        <div>
            <?php if($album){ ?>
            <section>
                <h3>Albums</h3>
                <?php
                foreach ($album as $a){
                    echo "<li><a href=\"?interpret=".$theOnlyOneName."&amp;album=".$a["albumName"]."\">".$a["albumName"]."</a></li>";
                }
                ?>
            </section>
            <?php } 
             if ($tracks){?>
            <section>
                <h3>Songs</h3>
                <?php
                foreach ($tracks as $t){
                    echo "<li><a href=\"?interpret=".$theOnlyOneName."&amp;album=".$t["albumName"]."\">".$t["trackName"]."</a></li>";
                }
                ?>
            </section>
            <?php } 
             if ($genres){?>
            <section>
                <h3>Genres</h3>
                <ul>
                <?php 
                    foreach ($genres as $g){
                        echo "<li><a href=\"?genre=".preg_replace('/[ ]*&[ ]*/', '%26', $g["genreName"])."\">".$g["genreName"]."</a></li>";
                    }
                ?>
                </ul>
            </section>
            <?php } 
            if ($members){?>
            <section>
            <?php
                if($artist){?><h3>Member Of</h3><?php } 
                if($band){?><h3>Members</h3><?php }
                
                foreach ($members as $m){
                    echo "<li><a href=\"?interpret=".$m["memberName"]."\">".$m["memberName"]."</a></li>";
                }
            ?>
            </section>
            <?php } 
            if($instruments){ ?>
            <section>
                <h3>Instruments</h3>
                <?php
                foreach ($instruments as $instrument){
                    echo "<li><a href=\"?instrument=".$instrument["name"]."\">".$instrument["name"]."</a></li>";
                }
                ?>
            </section>
            <?php } ?>
        </div>
        <div>
            <?php if ($interprets){ ?>
            <section>
                <h3>Similar artists</h3>
                <ul>
                <?php
                foreach ($interprets as $i){
                    if(preg_match('/SoloArtist$/',$i["type"])){
                        echo "<li><a href=\"?interpret=".$i["artistName"]."\">".$i["artistName"]."</a>
                        <span>".round($i["genresNo"]*100/count($genres))."%</span></li>";
                    }
                }
                ?>
                </ul>
            </section>
            <section>
                <h3>Similar bands</h3>
                <ul>
                <?php
                foreach ($interprets as $i){
                    if(preg_match('/Band$/',$i["type"])){
                        echo "<li><a href=\"?interpret=".$i["artistName"]."\">".$i["artistName"]."</a>
                        <span>".round($i["genresNo"]*100/count($genres))."%</span></li>";
                    }
                }
                ?>
                </ul>
            </section>
            <?php } ?>
        </div>
    </div>
<?php }