<?php if(!$songMismatch){?>
<div id="results">
    <h2><?php echo $songOutput; ?></h2>
    <section>
        <ul>
        <?php
        if($songs){
            foreach($songs as $s){
                echo "<li><a href=\"?interpret=".$s["artistName"]."\">".$s["artistName"]."</a>, 
                album <a href=\"?interpret=".$s["artistName"]."&amp;album=".$s["albumName"]."\">".$s["albumName"]."</a>";
                if($s["trackName"]) {
                    echo ", song <a href=\"?interpret=".$s["artistName"]."&amp;album=".$s["albumName"]."&amp;song=".$s["trackName"]."\">".$s["trackName"]."</a>";
                }
                echo "</li>";
            }    
        } else if($albums){ ?>
        <h3>Songs</h3>
        <?php
            foreach($albums as $a){
                echo "<li><a href=\"?song=".$a["trackName"]."\">".$a["trackName"]."</a></li>";
            }
        }
        ?>
        </ul>
    </section>
</div>
<?php } ?>